### ISSUE TITLE
Authorize Tool pop-up has redundant tool information and debug information 

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#1129]
**Steps to reproduce the problem:**
1. Create an agent with any tool that requires authentication. 
2. Use  `Authorization Status` ->`Authorize Tool` option to authenticate with the tool.

In the Authorize Tool pop up presented to the user notice that the tool name appears in the top left corner which is not needed.
Also the debug information appears twice .

<img width="566" alt="Screenshot 2025-01-06 at 2 39 46 PM" src="https://github.com/user-attachments/assets/b3ab0337-3aab-41c3-b6d6-a9a2b90f1d16" />

**Expected Behavior:**
Remove the tool name that appears in the top left corner.
Debug information should not be presented twice.

**Comment by cjellick** [comment]
WRT the original bug, I think we are talking about the fact that the blue hover text is shown by default instead of just when you hover over the icon. I agree that that should be removed.

**Comment by ryanhopperlowe** [comment]
Addressed with #1152

**Comment by sangee2004** [comment]
@ryanhopperlowe I still see the  blue hover text is shown by default when Pre-Authenticate pop up page is presented

<img width="596" alt="Image" src="https://github.com/user-attachments/assets/e2a0287c-7561-443a-92d8-3fdcfac8012c" />


Reopening this issue to get this addressed.

**Comment by sangee2004** [comment]
This issue is addressed in latest builds

<img width="631" alt="Image" src="https://github.com/user-attachments/assets/3f307f73-6ea9-4068-94f1-22fcae8badb6" />
