### ISSUE TITLE
Broken Image & 404 Error When Searching Large Image in Chatbot Section.

### ISSUE THREAD

**Issue by shweta8996** [obot-platform/obot#1949]
Steps to Reproduce:

- Created Agent and move to Chatbot
- Move to the Chatbot Section.
- Search for "Give me image size 15MB" in the chatbot.
- Observe that the image appears broken in the search results.
- Click on the "Details" link below the broken image.
- In the output section, observe that only a single image link is displayed instead of a valid image.
- Copy the image link and paste it into the browser.
- Observe that the browser returns a 404 Page Not Found error.

Expected Result:
The uploaded image should display correctly in the chatbot search results.
Pasting the image link in the browser should load the image properly instead of a 404 error and Clicking on the "Details" link should show the correct image URL.

Actual Result:
The image appears broken in the search results.
The link, when opened in a browser, returns a 404 Page Not Found error and clicking "Details" only provides a single non-functional image link.

Please refer attachment:

https://github.com/user-attachments/assets/226a9922-7cc6-43b6-a23c-dd63ef49d59c

**Comment by shweta8996** [comment]
@cjellick The issue still exists, the image view is still broken and you can not see the images inside the chat
Another issue is when you try to download these images from the file workspace it gives an error that the file didn't exist on site.

https://github.com/user-attachments/assets/3558fb43-0826-4b6c-99bf-9fdf1500a16c

**Comment by cjellick** [comment]
@shweta8996 make sure you kick these back to the Triage column

**Comment by cjellick** [comment]
@g-linville can you look at this one? image gen continues to work for me, so i need you to dig into why its broken for @shweta8996

**Comment by g-linville** [comment]
Turns out this was just an authz issue. Fixed now.

**Comment by shweta8996** [comment]
It is still broken for me on obot.ai. Working with @g-linville to check if issue is specific to myobot only or still a general issue.

**Comment by shweta8996** [comment]
> It is still broken for me on obot.ai. Working with [@g-linville](https://github.com/g-linville) to check if issue is specific to myobot only or still a general issue.

Confirmed with @g-linville , The issue is broken in thread  and when user tries to click on the link it says 403 forbidden.

**Comment by shweta8996** [comment]
I have tested on obot.ai and I performed below the steps:
Created Agent and move to Chatbot
Move to the Chatbot Section.
Search for "Give me an image of Rocky mountain." in the chatbot.
The image appears in the search results.
Observe that image is not open when I clicked on image.
Please refer attachment:

https://github.com/user-attachments/assets/18cb20ef-fdfa-4872-9934-9cd8acd29ffc

**Comment by cjellick** [comment]
> Search for "Give me an image of Rocky mountain." in the chatbot.

Curiuos: why do you phrase this as "Search for"? What is actually being searched for? Do you mean to say "Enter the prompt"?

**Comment by cjellick** [comment]
Still broken? Worked for me

<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/74a520dd-66c1-48f2-9e52-c4c13adece6c" />

**Comment by shweta8996** [comment]
I have verified on https://main.acornlabs.com/ and it is working fine as expected.
The uploaded image is displayed correctly in the chatbot search results.
Please refer attachment:

https://github.com/user-attachments/assets/c82880bb-d4ee-440b-ad36-643d8d12269d
