### ISSUE TITLE
Bunch of log messages relating to `command not found` presented in obot logs for every chat message.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#4169]
Bunch of log messages relating to `command not found` presented in obot logs for every chat message.

**Steps to reproduce the problem:**
1. Connect with any MCP server and chat with it.

Notice that following set of `command not found` logs being shown in obot server logs for every chat message.

```
time="2025-09-05T21:10:26Z" level=info msg="Handled request: method POST, path /workspaces/list" id=b140b718-cefd-439e-b554-2fa2294a7759
time="2025-09-05T21:10:26Z" level=info msg="Handling request: method POST, path /workspaces/list" id=2871034d-a60a-45aa-9e72-068b781a5c9f
time="2025-09-05T21:10:26Z" level=info msg="Handled request: method POST, path /workspaces/list" id=2871034d-a60a-45aa-9e72-068b781a5c9f
/tmp/gptscript2122664180: line 7: .txt: command not found
/tmp/gptscript2122664180: line 7: .md: command not found
/tmp/gptscript2122664180: line 7: .csv: command not found
/tmp/gptscript2122664180: line 7: .json: command not found
time="2025-09-05T21:10:29Z" level=info msg="Handled request: method POST, path /evaluate" id=45658d19-142d-4e84-a292-5cc8f8ca458e
```

**Expected Behavior:**
Suppress thes `command not found` logs from being shown for every chat message.

**Comment by cjellick** [comment]
I know this is a non-issue, but it is annoying

**Comment by thedadams** [comment]
This was addressed by https://github.com/obot-platform/tools/pull/739

**Comment by sangee2004** [comment]
@thedadams I am still seeing this issue reproduce when testing with latest version of tool

<img width="460" height="306" alt="Image" src="https://github.com/user-attachments/assets/b28446ee-1949-4c13-a58b-f036c4b9469f" />

When chatting in any project , i see the following messages show up in obo logs

```
time="2025-09-12T21:51:11Z" level=info msg="Handled request: method POST, path /workspaces/list" id=cf64246c-8476-41ab-892c-1c722a243c19
/tmp/gptscript3781681391: line 7: .txt: command not found
/tmp/gptscript3781681391: line 7: .md: command not found
/tmp/gptscript3781681391: line 7: .csv: command not found
/tmp/gptscript3781681391: line 7: .json: command not found
time="2025-09-12T21:51:12Z" level=info msg="Handled request: method POST, path /evaluate" id=834702fe-929a-4654-9e25-d8f375c13caa
time="2025-09-12T21:51:13Z" level=info msg="Handling request: method POST, path /evaluate" id=d406d8a3-730d-4f51-8b73-40bc33c350a7
time="2025-09-12T21:51:13Z" level=info msg="Handled request: method POST, path /evaluate" id=d406d8a3-730d-4f51-8b73-40bc33c350a7
time="2025-09-12T21:51:18Z" level=info msg="Handling request: method POST, path /credentials/reveal" id=0023a968-0719-490f-bca7-13b2b877caed
time="2025-09-12T21:51:18Z" level=info msg="Handled request: method POST, path /credentials/reveal" id=0023a968-0719-490f-bca7-13b2b877caed
time="2025-09-12T21:51:18Z" level=error msg="Failed to send tools/list message to server ms1gxn6f: error from server: JSON RPC internal error: failed to send request: stdin is closed" logger=/app/pkg/api/handlers/mcpgateway/handler.go
time="2025-09-12T21:51:18Z" level=info msg="Handling request: method POST, path /evaluate" id=778aa234-22b0-4b0d-88c8-61baf7857072
time="2025-09-12T21:51:18Z" level=info msg="Handling request: method POST, path /workspaces/list" id=8216dc1a-9acc-4242-869c-2c1cc97509a0
time="2025-09-12T21:51:18Z" level=info msg="Handled request: method POST, path /workspaces/list" id=8216dc1a-9acc-4242-869c-2c1cc97509a0
time="2025-09-12T21:51:18Z" level=info msg="Handling request: method POST, path /workspaces/list" id=266e2d25-ad79-4310-961b-e01522ff139c
time="2025-09-12T21:51:18Z" level=info msg="Handled request: method POST, path /workspaces/list" id=266e2d25-ad79-4310-961b-e01522ff139c
/tmp/gptscript2578910781: line 7: .txt: command not found
/tmp/gptscript2578910781: line 7: .md: command not found
/tmp/gptscript2578910781: line 7: .csv: command not found
/tmp/gptscript2578910781: line 7: .json: command not found
```

**Comment by sangee2004** [comment]
This issue is addressed when testing with latest builds.
`command not found` messages are not seen in logs when chatting .
