### ISSUE TITLE
MCP connector ids are very long which show up in the Chat window (and in connection url string if they are not the first instance of mcp server deployed).

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#4348]
**Describe the bug**
MCP connector ids are very long which show up in the Chat window (and in connection url string if they are not the first instance of mcp server deployed).

**To Reproduce**

Scenario1:
1. As user1, Create a project with any MCP server - `Tavily Search` in my case.
2. Enable project sharing
3. As user2 , use project sharing link and create project.
4. Go to `My Connectors` view and chat with the `Tavily Search` connector from `Available Connector` list.

Notice that the project gets created with the MCP connector id which is very long and gets presented in the chat window.
<img width="1040" height="599" alt="Image" src="https://github.com/user-attachments/assets/ee475675-dc17-4d97-a597-ba18d161fff9" />

Scenario2:

1. As user1, Create a project with any MCP server - `Tavily Search` in my case.
2. Enable project sharing
3. As user2 , connect to `Tavily Search` MCP server .
4. Use project sharing link from step2 and create project.
5. Go to `My Connectors` view and chat with the  new `Tavily Search` instance that got created after step 4 from `Available Connector` list.

Notice that connection url presented is very long in this case.

<img width="665" height="517" alt="Image" src="https://github.com/user-attachments/assets/8141960d-bdb7-4fa8-acc6-29f48a57cbd8" />

**Expected behavior**
Can the MCP Connector ids that get created be made to smaller than what it is now so that they dont show up with this very long string in Chat view and connection URLs.

**Comment by cjellick** [comment]
spoke with @thedadams about this one. we want to move the id part off of the name and into a metadata field

**Comment by StrongMonkey** [comment]
I think this issue is already addressed. The connection url is now unique regards to the actual mcp server entry instead of mcp server id. And the chat no longer shows long mcp server id.

I tried with the latest main and can't no longer reproduce this.

**Comment by sangee2004** [comment]
@StrongMonkey I am able to still reproduce the issue mentioned in this bug when testing with latest build.


<img width="754" height="661" alt="Image" src="https://github.com/user-attachments/assets/10dc696a-3ade-48e6-8470-fd55a732a24a" />

<img width="1429" height="867" alt="Image" src="https://github.com/user-attachments/assets/9e1061b4-a964-4a6d-ba81-9cd1a17a19b7" />

**Comment by StrongMonkey** [comment]
The first issue is caused by the fact that we use mcpserver + mcpid to name project, if you launch chat with a mcp server. For mcp server created from project sharing, the id is too long so it makes project name unfriendly. We seems to do this on purpose because we rely on unique project name to avoid launch duplicated project. 

The second one is that we will use mcp id as connect url is there exists a mcp server that is using the same catalog entry. By default it seems to be using catalog entry id but if there is conflict, it will fallback to use mcp id, which is a long id we assigned. 

Both will probably need some thoughts before working on the improvement.

**Comment by cjellick** [comment]
Closing because this issue applies to the legacy Obot Chat, Projects, Tasks, or Project Sharing experience, which has been removed. Obot Agent is also being deprecated in favor of the new Hosted Agent framework. If equivalent behavior is reproducible with Hosted Agents, please open a new issue against that framework.
